apiVersion: v1
kind: Service
metadata:
  name: cassandra
  labels:
    {{- include "cassandra.labels" . | nindent 4 }}
spec:
  clusterIP: "None"
  ports:
  - port: 9042 
  selector:
    {{- include "cassandra.selectorLabels" . | nindent 4 }}
